//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPAddressPool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPAddressPool()
        {
            this.LogBlockedIP = new HashSet<LogBlockedIP>();
            this.LogIPAllocation = new HashSet<LogIPAllocation>();
            this.LogIPAllocation1 = new HashSet<LogIPAllocation>();
            this.ServerIP = new HashSet<ServerIP>();
            this.Server = new HashSet<Server>();
        }
    
        public int Id { get; set; }
        public string IPAddress { get; set; }
        public string Status { get; set; }
        public string Gateway { get; set; }
        public string Subnetmask { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogBlockedIP> LogBlockedIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogIPAllocation> LogIPAllocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogIPAllocation> LogIPAllocation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServerIP> ServerIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Server> Server { get; set; }
        public virtual Account Account { get; set; }
    }
}
