//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogRequest()
        {
            this.LogConfirmedRequest = new HashSet<LogConfirmedRequest>();
            this.LogAppointment = new HashSet<LogAppointment>();
        }
    
        public int LogId { get; set; }
        public Nullable<int> RequestType { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> RequestedTime { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> AppointmentTime { get; set; }
        public string AppointmentStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogConfirmedRequest> LogConfirmedRequest { get; set; }
        public virtual RequestType RequestType1 { get; set; }
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogAppointment> LogAppointment { get; set; }
    }
}
