//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogServerMoving
    {
        public int LogId { get; set; }
        public Nullable<int> ServerId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> MovedLocation { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Server Server { get; set; }
        public virtual Account Account { get; set; }
    }
}
