//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerAttribute
    {
        public int AttributeId { get; set; }
        public Nullable<int> ServerId { get; set; }
        public string AttributeName { get; set; }
        public string AttributeValue { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
    
        public virtual Server Server { get; set; }
    }
}
