//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Server()
        {
            this.LogBlockedIP = new HashSet<LogBlockedIP>();
            this.LogConfirmedRequest = new HashSet<LogConfirmedRequest>();
            this.LogIPAllocation = new HashSet<LogIPAllocation>();
            this.LogServerDelivery = new HashSet<LogServerDelivery>();
            this.LogServerMoving = new HashSet<LogServerMoving>();
            this.LogUpgradedServer = new HashSet<LogUpgradedServer>();
            this.ServerAttribute = new HashSet<ServerAttribute>();
            this.ServerIP = new HashSet<ServerIP>();
        }
    
        public int ServerId { get; set; }
        public int CustomerId { get; set; }
        public string Maker { get; set; }
        public string Modern { get; set; }
        public string Power { get; set; }
        public int Size { get; set; }
        public string Status { get; set; }
        public Nullable<int> DefaultIP { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogBlockedIP> LogBlockedIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogConfirmedRequest> LogConfirmedRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogIPAllocation> LogIPAllocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogServerDelivery> LogServerDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogServerMoving> LogServerMoving { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogUpgradedServer> LogUpgradedServer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServerAttribute> ServerAttribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServerIP> ServerIP { get; set; }
        public virtual IPAddressPool IPAddressPool { get; set; }
        public virtual Location Location { get; set; }
        public virtual Account Account { get; set; }
    }
}
