//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IMS.Resources.Pages", typeof(Pages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMS.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeIndex {
            get {
                return ResourceManager.GetString("HomeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of IP Addresses.
        /// </summary>
        public static string IPIndex {
            get {
                return ResourceManager.GetString("IPIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Locations.
        /// </summary>
        public static string LocationIndex {
            get {
                return ResourceManager.GetString("LocationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Racks.
        /// </summary>
        public static string RackIndex {
            get {
                return ResourceManager.GetString("RackIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Add Server.
        /// </summary>
        public static string RequestAddServer {
            get {
                return ResourceManager.GetString("RequestAddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Request.
        /// </summary>
        public static string RequestCreate {
            get {
                return ResourceManager.GetString("RequestCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request History.
        /// </summary>
        public static string RequestHistory {
            get {
                return ResourceManager.GetString("RequestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Requests.
        /// </summary>
        public static string RequestIndex {
            get {
                return ResourceManager.GetString("RequestIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Detail.
        /// </summary>
        public static string ServerDetail {
            get {
                return ResourceManager.GetString("ServerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Servers.
        /// </summary>
        public static string ServerIndex {
            get {
                return ResourceManager.GetString("ServerIndex", resourceCulture);
            }
        }
    }
}
