//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TForceAlliance.Xyz.EyeSnipp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TForceAlliance.Xyz.EyeSnipp.Resources.Pages", typeof(Pages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asp .NET Examples.
        /// </summary>
        public static string AspNet {
            get {
                return ResourceManager.GetString("AspNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asp .NET AJAX Form.
        /// </summary>
        public static string AspNetAjaxForm {
            get {
                return ResourceManager.GetString("AspNetAjaxForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BootSnipp Code Snipset.
        /// </summary>
        public static string BootSnipp {
            get {
                return ResourceManager.GetString("BootSnipp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkboxes decoration with no Javascript.
        /// </summary>
        public static string BootSnippCheckBox1 {
            get {
                return ResourceManager.GetString("BootSnippCheckBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkboxes decoration with no Javascript (Animated).
        /// </summary>
        public static string BootSnippCheckBox2 {
            get {
                return ResourceManager.GetString("BootSnippCheckBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkboxes decoration with no Javascript (Color).
        /// </summary>
        public static string BootSnippCheckBox3 {
            get {
                return ResourceManager.GetString("BootSnippCheckBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeIndex {
            get {
                return ResourceManager.GetString("HomeIndex", resourceCulture);
            }
        }
    }
}
